import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-marketplace-seller-fee-reimbursement-recovery",
  "engine": "recovery",
  "title": "Marketplace Seller Fee & Reimbursement Recovery",
  "shortTitle": "Marketplace Recovery OS",
  "tagline": "Recover fulfillment losses, fee errors, return leakage, and missed marketplace reimbursements",
  "industry": "Ecommerce Marketplace Finance",
  "uiPort": 4558,
  "apiPort": 5558,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "Marketplace fee exceptions traced from settlement lines to reviewed policies and later credit evidence",
  "valueNarrative": "Reconcile listings, orders, fulfillment events, inventory ledgers, returns, fee schedules, settlements, and reimbursement policies.",
  "calculation": {
    "actualKey": "reimbursedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Marketplace reimbursed amount",
    "expectedLabel": "Policy-supported recovery",
    "varianceLabel": "Unrecovered marketplace value",
    "direction": "expected-minus-actual",
    "finding": "Inventory, order, return, settlement, and policy evidence indicate unrecovered seller value.",
    "actions": [
      "Reconstruct the SKU-level event timeline",
      "Apply effective marketplace fee and reimbursement policies",
      "Submit the evidence-complete reimbursement case",
      "Reconcile settlement credit and root cause"
    ]
  }
},[
feature("marketplace-account-and-policy-library","MRO01","Marketplace account and policy library","Reconcile marketplace account and policy library using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed marketplace account and policy library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("sku-and-listing-registry","MRO02","SKU and listing registry","Reconcile sku and listing registry using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed sku and listing registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("order-and-settlement-ingestion","MRO03","Order and settlement ingestion","Reconcile order and settlement ingestion using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed order and settlement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("fulfillment-inventory-ledger","MRO04","Fulfillment inventory ledger","Reconcile fulfillment inventory ledger using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed fulfillment inventory ledger decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("inbound-shortage-detection","MRO05","Inbound shortage detection","Reconcile inbound shortage detection using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed inbound shortage detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("lost-and-damaged-inventory-recovery","MRO06","Lost and damaged inventory recovery","Reconcile lost and damaged inventory recovery using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed lost and damaged inventory recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("return-and-refund-reconciliation","MRO07","Return and refund reconciliation","Reconcile return and refund reconciliation using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed return and refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("fulfillment-fee-recalculation","MRO08","Fulfillment fee recalculation","Reconcile fulfillment fee recalculation using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed fulfillment fee recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("storage-and-aged-inventory-fee-audit","MRO09","Storage and aged-inventory fee audit","Reconcile storage and aged-inventory fee audit using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed storage and aged-inventory fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("commission-and-referral-fee-audit","MRO10","Commission and referral fee audit","Reconcile commission and referral fee audit using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed commission and referral fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("duplicate-deduction-detection","MRO11","Duplicate deduction detection","Reconcile duplicate deduction detection using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed duplicate deduction detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("reimbursement-eligibility-engine","MRO12","Reimbursement eligibility engine","Reconcile reimbursement eligibility engine using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed reimbursement eligibility engine decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("claim-package-and-submission","MRO13","Claim package and submission","Reconcile claim package and submission using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed claim package and submission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("settlement-credit-reconciliation","MRO14","Settlement credit reconciliation","Reconcile settlement credit reconciliation using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed settlement credit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]}),
feature("sku-and-marketplace-leakage-analytics","MRO15","SKU and marketplace leakage analytics","Reconcile sku and marketplace leakage analytics using marketplace fee schedules, orders, fulfillment scans, inventory adjustments, returns, settlements, and reimbursement policies.","Produce a governed sku and marketplace leakage analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["marketplace","Marketplace","text","GlobalMart US"],["skuEvent","SKU / Event","text","SKU-88420 / EVT-2108"],["reimbursedAmount","Reimbursed Amount","currency",128000],["eligibleAmount","Eligible Recovery","currency",176500]],{amountField:"reimbursedAmount",subjects:["Fulfillment inventory loss","Customer return mismatch","Inbound receiving shortage","Fee overcharge","Destroyed inventory claim"]})
]);
